# Generated by Django 5.2.5 on 2025-10-02 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content', models.TextField(verbose_name='Текст сообщения')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('status', models.CharField(choices=[('sent', 'Отправлено'), ('delivered', 'Доставлено'), ('read', 'Прочитано')], default='sent', max_length=20, verbose_name='Статус')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='messages/attachments/', verbose_name='Вложение')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender'], name='message_mes_sender__902e29_idx'), models.Index(fields=['receiver'], name='message_mes_receive_fa9ee6_idx'), models.Index(fields=['is_read'], name='message_mes_is_read_4f7689_idx'), models.Index(fields=['status'], name='message_mes_status_92ccc6_idx')],
            },
        ),
    ]
