version: '3.8'

services:
  db:
    image: postgres:14
    container_name: medhub_db
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: medhub_redis
    restart: unless-stopped
    expose:
      - "6379"  # Internal use only

  web:
    build:
      context: .
    container_name: medhub_backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    expose:
      - "8000"
    volumes:
      - .:/app
      - static_data:/app/staticfiles
      - media_data:/app/mediafiles
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: medhub_nginx
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      web:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data:
  static_data:
  media_data:
