# Generated by Django 5.2.5 on 2025-10-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Регион')),
                ('slug', models.SlugField(unique=True, verbose_name='Псевдоним')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='core_region_slug_a28158_idx'), models.Index(fields=['is_active'], name='core_region_is_acti_707308_idx')],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=100, verbose_name='Город')),
                ('slug', models.SlugField(verbose_name='Псевдоним')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='core.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['region__name', 'name'],
                'indexes': [models.Index(fields=['slug'], name='core_city_slug_72b672_idx'), models.Index(fields=['is_active'], name='core_city_is_acti_f34fc7_idx')],
                'unique_together': {('region', 'name')},
            },
        ),
    ]
