# Generated by Django 5.2.5 on 2025-08-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Пациент'), ('doctor', 'Врач'), ('institution_admin', 'Администратор учреждения'), ('super_admin', 'Супер администратор')], db_index=True, default='patient', max_length=20),
        ),
    ]
