# Generated by Django 5.2.5 on 2025-08-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_is_active_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('patient', 'Пациент'), ('doctor', 'Врач'), ('institution_admin', 'Администратор учреждения'), ('super_admin', 'Супер администратор')], db_index=True, default='patient', max_length=30),
        ),
    ]
