# Generated by Django 5.2.5 on 2025-10-04 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='Комментарий пациента')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принята'), ('rejected', 'Отклонена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус заявки')),
                ('appointment_time', models.DateTimeField(blank=True, null=True, verbose_name='Время приёма')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to=settings.AUTH_USER_MODEL, verbose_name='Врач')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Заявка на приём',
                'verbose_name_plural': 'Заявки на приём',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='appointment_status_e3665a_idx'), models.Index(fields=['doctor'], name='appointment_doctor__26d963_idx'), models.Index(fields=['patient'], name='appointment_patient_4768df_idx')],
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
