# Generated by Django 5.2.5 on 2025-08-28 09:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequest',
            name='appointment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время приёма'),
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddIndex(
            model_name='appointmentrequest',
            index=models.Index(fields=['status'], name='appointment_status_e3665a_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentrequest',
            index=models.Index(fields=['doctor'], name='appointment_doctor__26d963_idx'),
        ),
        migrations.AddIndex(
            model_name='appointmentrequest',
            index=models.Index(fields=['patient'], name='appointment_patient_4768df_idx'),
        ),
    ]
