# Generated by Django 5.2.5 on 2025-08-28 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('metric', models.CharField(max_length=255, verbose_name='Название метрики')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('period_start', models.DateField(verbose_name='Начало периода')),
                ('period_end', models.DateField(verbose_name='Конец периода')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('target_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Статистический показатель',
                'verbose_name_plural': 'Статистические показатели',
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['metric', 'period_start', 'period_end'], name='statistics__metric_cc531d_idx'), models.Index(fields=['target_ct', 'target_id'], name='statistics__target__1b3fd2_idx')],
                'unique_together': {('metric', 'period_start', 'period_end', 'target_ct', 'target_id')},
            },
        ),
    ]
