# Generated by Django 5.2.5 on 2025-10-02 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('institution_type', models.CharField(choices=[('hospital', 'Больница'), ('clinic', 'Клиника'), ('laboratory', 'Лаборатория'), ('other', 'Другое')], max_length=20, verbose_name='Тип учреждения')),
                ('ownership_type', models.CharField(choices=[('state', 'Государственное'), ('private', 'Частное')], max_length=20, verbose_name='Форма собственности')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/logos/', verbose_name='Логотип')),
                ('is_top', models.BooleanField(default=False, verbose_name='ТОП учреждение')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='core.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждения',
                'ordering': ['-is_top', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления')),
                ('name', models.CharField(max_length=255, verbose_name='Отделение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='institutions.institution', verbose_name='Учреждение')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'ordering': ['institution__name', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['slug'], name='institution_slug_6f1103_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['is_active'], name='institution_is_acti_c588f0_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['institution_type'], name='institution_institu_2be7c1_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='institution_is_acti_930f7e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('institution', 'name')},
        ),
    ]
