# Generated by Django 5.2.5 on 2025-08-25 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Псевдоним')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('institution_type', models.CharField(choices=[('hospital', 'Больница'), ('clinic', 'Клиника'), ('laboratory', 'Лаборатория'), ('other', 'Другое')], max_length=20, verbose_name='Тип учреждения')),
                ('ownership_type', models.CharField(choices=[('state', 'Государственное'), ('private', 'Частное')], max_length=20, verbose_name='Форма собственности')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/logos/', verbose_name='Логотип')),
                ('is_top', models.BooleanField(default=False, verbose_name='ТОП учреждение')),
                ('is_active', models.BooleanField(default=False, verbose_name='Проверено и активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Учреждение',
                'verbose_name_plural': 'Учреждения',
                'ordering': ['-is_top', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Отделение')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='institutions.institution', verbose_name='Учреждение')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
                'unique_together': {('institution', 'name')},
            },
        ),
    ]
