# Generated by Django 5.2.5 on 2025-08-28 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_deleted_at_city_is_active_region_deleted_at_and_more'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['institution__name', 'name'], 'verbose_name': 'Отделение', 'verbose_name_plural': 'Отделения'},
        ),
        migrations.RemoveField(
            model_name='institution',
            name='region',
        ),
        migrations.AddField(
            model_name='department',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AddField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddField(
            model_name='institution',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions', to='core.city', verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='institution',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата удаления'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='institution_is_acti_930f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['slug'], name='institution_slug_6f1103_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['is_active'], name='institution_is_acti_c588f0_idx'),
        ),
        migrations.AddIndex(
            model_name='institution',
            index=models.Index(fields=['institution_type'], name='institution_institu_2be7c1_idx'),
        ),
    ]
